### PR TITLE
Fix issue #13

### PR DESCRIPTION
**Pull request by aprimadi**
These are the changes:
    - Fix Scheduled For is displaying EnqueuedAt instead of RunAt
    - Update react version to 16.2.0
    - Use yarn
    - Upgrade to webpack 2.0
    - Use enzyme for unit testing (to support React version 16.2.0)

### CODE REVIEW

**Comment by freedomofkeima** [comment]
Hi there 😃 

I just noticed that the import is changed from `"github.com/gocraft/work/webui"` to `github.com/dexcodeinc/work/webui`. Is this intentional? 👀 

Thank you!

**Comment by aprimadi** [comment]
Hi @freedomofkeima, thank you for noticing, I use that import on the fork of the project. @shdunning please fix the import and sorry for the trouble.

**Comment by shdunning** [comment]
@freedomofkeima good catch! @aprimadi imports have been fixed.

**Comment by kumarsiva07** [comment]
@aprimadi @shdunning Scheduled for is not in local time. Also Is there anyway to add scheduled job to queue immediately to process?

**Pull request merged**
